### PR TITLE
fix: Update versions and import timing

### PR DESCRIPTION
**Pull request by chrisjshull**

### CODE REVIEW

**Review by wangela — CHANGES_REQUESTED** [review]
Please resolve conflicts and we'll merge!

**Comment by chrisjshull** [comment]
PTAL

**Review by wangela — APPROVED** [review]

**Review by wangela — CHANGES_REQUESTED** [review]
[Tests are failing](https://github.com/googlemaps/js-samples/actions/runs/6762565177/job/18378676105?pr=1581) for:

- place-autocomplete-element
- place-autocomplete-map
- place-text-search
- boundaries-text-search

**Comment by chrisjshull** [comment]
All breaking for unrelated reasons, but should be fixed now.

**Review by wangela — APPROVED** [review]

**Pull request merged**
